# Generated by Django 3.2.4 on 2021-07-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='article',
            name='author_name',
            field=models.CharField(default='anonimus', max_length=50, verbose_name='Имя автора'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='anons',
            field=models.CharField(max_length=200, verbose_name='Анонс'),
        ),
    ]
